services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    labels:
      - "traefik.http.routers.grafana.rule=Host(`monitoring.pachovit.com`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
    networks:
      - echopages
    depends_on:
      - loki
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - ${INFRA_DIR}/monitoring-config/grafana/provisioning:/etc/grafana/provisioning
      - ${INFRA_DIR}/monitoring-config/grafana/grafana.ini:/etc/grafana/grafana.ini

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ${INFRA_DIR}/monitoring-config/loki.yml:/etc/loki/local-config.yaml
    networks:
      - echopages

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${INFRA_DIR}/monitoring-config/promtail.yml:/etc/promtail/config.yml
    networks:
      - echopages

networks:
  echopages:
    external: true